// <auto-generated />
using System;
using ItlaPrime.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItlaPrime.Database.Migrations
{
    [DbContext(typeof(ItlaPrimeContext))]
    partial class ItlaPrimeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ItlaPrime.Database.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);
                });

            modelBuilder.Entity("ItlaPrime.Database.Entities.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Producers", (string)null);
                });

            modelBuilder.Entity("ItlaPrime.Database.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PrimaryGenreID")
                        .HasColumnType("int");

                    b.Property<int>("ProducerID")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryGenreID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryGenreID");

                    b.HasIndex("ProducerID");

                    b.HasIndex("SecondaryGenreID");

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("ItlaPrime.Database.Entities.Series", b =>
                {
                    b.HasOne("ItlaPrime.Database.Entities.Genre", "PrimaryGenre")
                        .WithMany("PrimarySeries")
                        .HasForeignKey("PrimaryGenreID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItlaPrime.Database.Entities.Producer", "Producer")
                        .WithMany("Series")
                        .HasForeignKey("ProducerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItlaPrime.Database.Entities.Genre", "SecondaryGenre")
                        .WithMany("SecondarySeries")
                        .HasForeignKey("SecondaryGenreID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PrimaryGenre");

                    b.Navigation("Producer");

                    b.Navigation("SecondaryGenre");
                });

            modelBuilder.Entity("ItlaPrime.Database.Entities.Genre", b =>
                {
                    b.Navigation("PrimarySeries");

                    b.Navigation("SecondarySeries");
                });

            modelBuilder.Entity("ItlaPrime.Database.Entities.Producer", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
